---

- hosts: all
  become: yes

  vars_prompt:
    - name: username
      prompt: "User name"
      private: no
    - name: password
      prompt: "Password"

  tasks:
    - name: Disable all Yum repos
      command: yum-config-manager --disable '*'

  roles:
    - role: maven
      vars:
        maven_master_password: "{{ password }}"