---

- hosts: all
  become: yes

  vars_prompt:
    - name: username
      prompt: "User name"
      private: no
    - name: password
      prompt: "Password"

  tasks:
    - name: Disable all Yum repos
      command: yum-config-manager --disable '*'

    - include_role:
        name: docker
      vars:
        daemon:
          insecure-registries:
            - registry.local
          registry-mirrors:
            - https://registry.local

    - include_role:
        name: instantclient
      vars:
        tnsnames:
          - sid: CDB1
            name: cdb1
            service: pdb1
            host: localhost

    - name: Encrypt password for Maven
      command: "mvn --encrypt-password {{ password }}"
      register: mvn_encrypted_password_cmd
      become: no

    - set_fact:
        mvn_encrypted_password: "{{ mvn_encrypted_password_cmd.stdout }}"

    - include_role:
        name: maven
        tasks_from: maven_config
      vars:
        user: vagrant
        settings:
          interactiveMode: "false"
          pluginGroups:
            - org.sonarsource.scanner.maven
          servers:
            - id: snapshots
              username: "{{ username }}"
              password: "{{ mvn_encrypted_password }}"
            - id: releases
              username: "{{ username }}"
              password: "{{ mvn_encrypted_password }}"
          mirrors:
            - id: nexus3
              mirrorOf: '*'
              url: https://nexus3.local/repository/maven-public/
          profiles:
            - id: sonar
              activation:
                activeByDefault: "true"
              properties:
                sonar.host.url: https://sonarqube.local/
                sonar.login: "{{ username }}"
                sonar.password: "{{ mvn_encrypted_password }}"
            - id: nexus3
              repositories:
                - id: central
                  url: https://nexus3.local/repository/maven-public/
                  releases:
                    enabled: "true"
                  snapshots:
                    enabled: "true"
              pluginRepositories:
                - id: central
                  url: https://nexus3.local/repository/maven-public/
                  releases:
                    enabled: "true"
                  snapshots:
                    enabled: "true"
          activeProfiles:
            - nexus3

    - include_role:
        name: node
      vars:
        npmrc:
          npm_registry: https://nexus3.local/repository/npm-all
          sass_binary_site: https://nexus3.local/repository/node-sass-binaries
          strict_ssl: "false"

