---

- hosts: all
  become: yes

  tasks:
    - include_role:
        name: docker-oracle

    - include_role:
        name: docker-weblogic

    - include_role:
        name: instantclient
      vars:
        tnsnames:
          - name: ORCLCDB
            host: localhost
          - name: ORCLPDB1
            host: localhost
