---

- name: Install DVC repository
  command:
    cmd: dnf config-manager --add-repo https://dvc.org/rpm/dvc.repo
    creates: /etc/yum.repos.d/dvc.repo
    warn: false

- name: Install DVC (Data Version Control)
  package:
    name: dvc
    state: present

- name: Check status of DVC global config file
  stat:
    path: /etc/xdg/dvc/config
  register: dvc_system_config

- name: Configure DVC
  block:
    - name: Disable anlytics
      command: dvc config --system core.analytics false
    - name: Disable update checks
      command: dvc config --system core.check_update false
  when: not dvc_system_config.stat.exists

- name: Configure DVC settings
  include: dvc_config.yml
  with_items: "{{ dvc_users }}"
  loop_control:
    loop_var: user

- name: Copy DVC example project
  include: dvc_example.yml
  with_items: "{{ dvc_users }}"
  loop_control:
    loop_var: user