---

- name: Install Scala
  command: dnf install -y https://downloads.lightbend.com/scala/2.13.1/scala-2.13.1.rpm
  args:
    warn: false
    creates: /usr/bin/scala

- name: Install SBT
  command: dnf install -y https://dl.bintray.com/sbt/rpm/sbt-1.3.0.rpm
  args:
    warn: false
    creates: /usr/bin/sbt

- name: Create SBT settings
  include: sbt_config.yml
  with_items: "{{ sbt_users }}"
  loop_control:
    loop_var: user