---

- name: Install Docker CE repository
  command:
    cmd: dnf config-manager --add-repo=https://download.docker.com/linux/centos/docker-ce.repo
    warn: false
  args:
    creates: /etc/yum.repos.d/docker-ce.repo

- name: Install Docker CE
  block:
    - name: Install container-selinux package
      package:
        name: container-selinux
        state: present
    - name: Disable container-tools module
      command: dnf -y module disable container-tools
      args:
        warn: false
      changed_when: false
    - name: Install Docker CE packages
      package:
        name: "{{ item }}"
        state: present
      with_items:
        - docker-ce
        - docker-ce-cli
        - containerd.io

- name: Configure Docker daemon config
  block:
    - name: Create Docker config directory
      file:
        path: /etc/docker
        state: directory
    - name: Create daemon.json
      template:
        src: daemon.json.j2
        dest: /etc/docker/daemon.json
      notify: restart docker
    - name: Reload systemd config
      systemd:
        daemon_reload: yes
  when: daemon is defined

- name: Configure Docker daemon flags
  block:
    - name: Configure Docker command line
      lineinfile:
        path: /usr/lib/systemd/system/docker.service
        regexp: '^(ExecStart=/usr/bin/dockerd).*$'
        line: 'ExecStart=/usr/bin/dockerd {{ docker_options }}'
    - name: Reload systemd config
      systemd:
        daemon_reload: yes
  when: docker_options is defined

- name: Ensure Docker daemon is started at boot and running
  service:
    name: docker
    state: started
    enabled: yes

- name: Add Docker users to the docker group
  user:
    name: "{{ item }}"
    groups: docker
    append: true
  with_items: "{{ docker_users }}"

- name: Configure Docker CLI
  include: docker_config.yml
  with_items: "{{ docker_users }}"
  loop_control:
    loop_var: user
  when: config is defined

#- name: Install Python Docker SDK (for Ansible)
#  package:
#    name: python-docker-py
#    state: present

- name: Install Python Docker SDK (for Ansible)
  pip:
    name: docker

- name: Install Docker Compose
  get_url:
    url: https://github.com/docker/compose/releases/download/{{ docker_compose_version }}/docker-compose-Linux-x86_64
    dest: /usr/local/bin/docker-compose
    mode: 0755

- name: Add cleanup script
  copy:
    src: docker-clean.sh
    dest: /usr/local/bin
    mode: 0755