---

#- hosts: all
#  become: yes
#  tasks:
#    - name: Extend the /var logical volume
#      lvol:
#        vg: vg_system
#        lv: var
#        size: 20G
#        resizefs: true

- hosts: all
  become: yes
  roles:
    - docker-oracle
    - docker-weblogic
    - instantclient



