---

- name: Test if saved Weblogic Docker image exists
  stat:
    path: "{{ docker_image_directory }}/weblogic-12213-dev.tgz"
  register: docker_image_wls

- name: Load Weblogic Docker image
  docker_image:
    name: container-registry.oracle.com/middleware/weblogic:12.2.1.3-dev
    load_path: "{{ docker_image_directory }}/weblogic-12213-dev.tgz"
  when: docker_image_wls.stat.exists
  register: docker_load_wls

- name: Retag Weblogic Docker image
  shell: docker tag container-registry.oracle.com/middleware/weblogic:12.2.1.3-dev oracle/weblogic:12.2.1.3-dev
  when: docker_load_wls.changed