---

- name: Create .m2 directory
  file:
    path: "~{{ user }}/.m2"
    state: directory
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: 0755

- name: Create settings.xml
  template:
    src: settings.xml.j2
    dest: "~{{ user }}/.m2/settings.xml"
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: 0644
  when: settings is defined

- name: Generate Maven master password
  shell:  "cat /dev/urandom | tr -cd '[:print:]' | head -c 32 | {{ m2_home }}/bin/mvn --encrypt-master-password -"
  register: maven_master_password_cmd

- name: Create settings-security.xml
  template:
    src: settings-security.xml.j2
    dest: "~{{ user }}/.m2/settings-security.xml"
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: 0600
