---

- hosts: all
  become: yes
  tasks:
    - name: Extend the /var logical volume
      lvol:
        vg: vg_system
        lv: var
        size: 30G
        resizefs: true
    - name: Extend the /tmp logical volume
      lvol:
        vg: vg_system
        lv: tmp
        size: 3G
        resizefs: true
    - name: Extend the /home logical volume
      lvol:
        vg: vg_system
        lv: home
        size: 5G
        resizefs: true

- hosts: all
  become: yes
  roles:
    - angular-cli
#    - cntlm
    - docker
    - dvc
    - maven
#    - minikube
    - nodejs
    - openjdk
    - python3
    - tools