---

- hosts: all
  become: yes
  roles:
    - docker-oracle

- hosts: all
  become: yes
  tasks:
    - include_role:
        name: instantclient
      vars:
        tnsnames:
          - name: ORCLCDB
            host: localhost
          - name: ORCLPDB1
            host: localhost
